name: SweetWarehouse
version: '${version}'
main: top.mrxiaom.sweet.warehouse.SweetWarehouse
api-version: 1.13
depend: [ Vault ]
softdepend: [ PlaceholderAPI, MythicMobs ]
authors: [ MrXiaoM ]
commands:
  warehouse:
    description: awa
    aliases: [ yc ]
